### ISSUE TITLE
How much vram is needed

### ISSUE THREAD

**Issue by kackbob** [KAIST-VICLab/FMA-Net#12]
Hi, thank you for your great work!
 
How much vram do I need when testing?

**Comment by GeunhyukYouk** [comment]
Hi, thank you for your interest in our work!

To test REDS4 (180x320 video sequence) in our [environment](https://github.com/KAIST-VICLab/FMA-Net?tab=readme-ov-file#requirements), you'll need about 5GB of GPU memory. Note that this may vary slightly depending on the OS and software version, and it also varies based on the size of the test video.

**Comment by GeunhyukYouk** [comment]
I will close this issue as there has been no further discussion. Please re-open the issue if there are additional comments.
