### ISSUE TITLE
Dosent work with sd resolution (768 576) oom on 24gb nvidia

### ISSUE THREAD

**Issue by gvonkreisler** [KAIST-VICLab/FMA-Net#14]
This work was supported by the Institute of Information & communications Technology Planning & Evaluation (IITP) grant funded by the Korea government (MSIT): No. 2021-0-00087, Development of high-quality conversion technology for       **SD/HD**       low-quality media and No. RS2022-00144444, Deep Learning Based Visual Representational Learning and Rendering of Static and Dynamic Scenes.

**Comment by GeunhyukYouk** [comment]
I will close this issue as there has been no further discussion. Please re-open the issue if there are additional comments.
