### ISSUE TITLE
Can you show me the detailed hierarchy of REDS of data? I want to configure my own dataset.

### ISSUE THREAD

**Issue by meiwu5** [KAIST-VICLab/FMA-Net#16]
Can you show me the detailed hierarchy of REDS of data? I want to configure my own dataset.

**Comment by GeunhyukYouk** [comment]
Thank you for your interest in Fma-net.

I am currently on a business trip, but I will provide answers to the two issues you inquired about and explanations for retraining within a few days.

**Comment by GeunhyukYouk** [comment]
Hello, I apologize for the late response.

We use the REDS4 dataset, which has the exact same structure as the original REDS.

First, please download the [REDS](https://seungjunnah.github.io/Datasets/reds.html) dataset to './dataset'. Then, run this [code](https://github.com/KAIST-VICLab/FMA-Net/blob/main/preprocessing/generate_reds4.py) to generate REDS4.

The hierarchy of the generated REDS4 is as follows.

```
├──── dataset/
    ├──── REDS4/
       ├──── train_blur_bicubic/
          ├──── train/
             ├──── train_blur_bicubic/
                 ├──── X4/
                     ├──── 001/
                         ├──── 00000000.png
                         ├──── ...
                         ├──── 00000009.png/
                     ├──── 002/
                     ├──── ...

Additionally, it is also fine to modify the [REDS_Dataset](https://github.com/KAIST-VICLab/FMA-Net/blob/a7a595d88a64014022b8f04eaec0622e861b1a31/data.py#L25) class in [data.py](https://github.com/KAIST-VICLab/FMA-Net/blob/main/data.py).
