### ISSUE TITLE
Requeset for code to calculate tOF used in the paper

### ISSUE THREAD

**Issue by DachunKai** [KAIST-VICLab/FMA-Net#19]
Hi, could you provide the code or snippet to calculate tOF to measure temporal consistency? Thanks a lot!

**Comment by GeunhyukYouk** [comment]
We have already released the [code](https://github.com/KAIST-VICLab/FMA-Net/blob/main/utils.py) for calculating RGB PSNR, Y PSNR, SSIM, and tOF performance. The tOF measurement code is implemented based on the [TecoGAN](https://github.com/thunil/TecoGAN/blob/master/metrics.py) repository. 

Specifically, you can measure the four metrics simply by running the [test_quantitative_result](https://github.com/KAIST-VICLab/FMA-Net/blob/337bb45f56b1e550073eaa0dfaee199395a3606f/train.py#L266) function. You can find an example of execution [here](https://github.com/KAIST-VICLab/FMA-Net/blob/337bb45f56b1e550073eaa0dfaee199395a3606f/main.py#L57).
