### ISSUE TITLE
work

### ISSUE THREAD

**Issue by txy00001** [KAIST-VICLab/FMA-Net#2]
Hello, I saw your project, it feels very good to see the effect, I am also doing video-based deblurring related work, comparing the effect you showed with other algorithms and my own algorithm, I think this work makes me excited, and I am eager to know your inference time based on each frame of the video and the generality of the video, because many algorithms are based on the inherent video dataset, and cannot perform general inference on your own video, I don't know if your work has made improvements in this regard? It would be a great job if it was more generic, and I look forward to your source code

**Comment by KAIST-VICLab** [comment]
Thank you for your interest in FMA-Net.
Please refer to Table 1 in the [paper](https://arxiv.org/pdf/2401.03707.pdf) for the inference time.  Table 1 compares the inference time of FMA-Net with existing models, and unfortunately, the improvement in inference speed of FMA-Net compared to existing models is not significant.
