### ISSUE TITLE
How to get the Average Motion Magnitude of optical flow in Tab. 3?

### ISSUE THREAD

**Issue by QZ1-boy** [KAIST-VICLab/FMA-Net#20]
Could you tell us how to calculate the Average Motion Magnitude of optical flow for obtaining the PSNR/ tOF results in Tab. 3 in the main paper?  

Besides, how to draw the average motion magnitude and PSNR of the Fig.8 in your Supplementary Material?

Thank you!

**Comment by GeunhyukYouk** [comment]
Hi, sorry for the late reply.

The average motion magnitude was obtained by averaging the absolute values of the optical flow acquired with the pretrained RAFT model.
The graph in Fig. 8 visualizes the trend line obtained through regression, and it can be drawn using Python, Excel, or similar tools.
