### ISSUE TITLE
Eta on code

### ISSUE THREAD

**Issue by nanowell** [KAIST-VICLab/FMA-Net#3]
Thank you for this research, I want to know about eta for code and weights?

**Comment by KAIST-VICLab** [comment]
Thank you for your interest in FMA-Net. 
Currently, the paper is under review, so we plan to upload the code and weights as soon as the results are available.

**Comment by ngaer** [comment]
Hi @KAIST-VICLab, we are looking forward to this model. Do you have a rough estimate of when the paper review will be finished?
