### ISSUE TITLE
When do we expect to get codes, and pre-trained models?

### ISSUE THREAD

**Issue by claymore07** [KAIST-VICLab/FMA-Net#6]
Hi,
I have been waiting on the codes or pre-trained models of your approach for more than two months, when do we expect to have the code?
Best Regards

**Comment by ahmadmustafaanis** [comment]
+1

**Comment by hardikdava** [comment]
+1

**Comment by Stars-WMX** [comment]
Me too

**Comment by kackbob** [comment]
+1

**Comment by vietpho** [comment]
+1

**Comment by DachunKai** [comment]
+1

**Comment by madgnot** [comment]
I think this fucking budy will never open their code

**Comment by GeunhyukYouk** [comment]
Hi,
I apologize for the delayed code release. 
We have just completed the release of the FMA-Net code, including training, testing, and pretrained model. 

Thank you for your interest in FMA-Net.
