### ISSUE TITLE
run on single video

### ISSUE THREAD

**Issue by ahmadmustafaanis** [KAIST-VICLab/FMA-Net#8]
hi, i see the evaluation/testing code but how can i run the pretrained model on a single video?

**Comment by Platorius** [comment]
I would also like to know that. 

How can we use this model (or our own trained one) to run it on a real video ?

**Comment by mehao** [comment]
I would also like to know that.

How can we use this model (or our own trained one) to run it on a real video ?

**Comment by GeunhyukYouk** [comment]
Hi,
We do not provide direct testing code for videos. However, there are two ways to address this.
Firstly, you can use tools like ffmpeg to convert the video into an image sequence and then utilize the [test_custom](https://github.com/KAIST-VICLab/FMA-Net?tab=readme-ov-file#testing) option we provide. 
Secondly, you can directly test the video using the [restoration_video_inference](https://zyhmmediting-zh.readthedocs.io/en/latest/autoapi/mmedit/apis/index.html#mmedit.apis.restoration_video_inference) function in the MMEditing library.

**Comment by ps3dood** [comment]
I think you need to reduce your resolution. VRAM  use absolutely balloons with resolution and frame count

**Comment by GeunhyukYouk** [comment]
I will close this issue as there has been no further discussion. Please re-open the issue if there are additional comments.
